### ISSUE TITLE
Compatibility with rollup and es6

### ISSUE THREAD

**Issue by joshhjacobson** [mljs/kmeans#13]
Hi,

I'm using Rollup to build an es6 module and when I go to build my files, I get the following error:
```
[!] Error: 'squared' is not exported by node_modules/ml-kmeans/node_modules/ml-distance-euclidean/euclidean.js
npm ERR! code ELIFECYCLEp/rollup/wiki/Troubleshooting#name-is-not-exported-by-module
npm ERR! errno 1kmeans/src/initialization.js (2:9)
```
I realize this could probably be handled using [rollup-plugin-commonjs](https://github.com/rollup/rollup-plugin-commonjs), but it looks like the issue has already been partially addressed in version 4.1. 

Your `distance-euclidean` repo builds a directory `lib-es6` but this is not present in `node_modules/ml-kmeans/node_modules/ml-distance-euclidean/` so it ends up using the default commonjs version.

Am I missing something here? Has `ml-kmeans` been tested with an es6 build?

Thanks,
Josh

**Comment by stropitek** [comment]
Hey,

Not sure what happened but I published in a hurry and my imports were wrong.

4.2.1 should be fine
