### ISSUE TITLE
does it works in n D

### ISSUE THREAD

**Issue by lpatiny** [mljs/kmeans#2]
In the userguide it seems it works on with x,y points. Is this correct ?

I would like to kluster r,g,b points.

**Comment by maasencioh** [comment]
@lpatiny It works on N dimesional points, the restriction it that has to be an array of (x,y,z,...) points, like in this example

```js
'use strict';

const kmeans = require('ml-kmeans');

let data = [[1, 1, 1], [1,2,1], [-1, -1, -1], [-1,-1,-1.5]];
let centers = [[1,2,1], [-1, -1, -1]]

let ans = kmeans(data, centers);
console.log(ans.clusters);
console.log(ans.centroids);
```
