### ISSUE TITLE
Change the parameters ?

### ISSUE THREAD

**Issue by lpatiny** [mljs/kmeans#3]
function kmeans(data, k, options)

options.initialisation
* array of your current centers
* 'random' (default value) : we take randomly k points of the data

**Comment by maasencioh** [comment]
random it's not a wise option, because kmeans results depends a lot of the inicialization centers, there are other algorithm that performs better and could be added as enhancement

**Comment by lpatiny** [comment]
OK we could change the 'default' later. Could be indeed better to take the 'more distant' objects.

**Comment by targos** [comment]
http://www.academia.edu/213823/Cluster_Center_Initialization_Algorithm_for_K_-means_clustering
