### ISSUE TITLE
Centroid value is NaN

### ISSUE THREAD

**Issue by anomepani** [mljs/kmeans#9]
Sometimes **KMeansResult's**  centroids value is NaN for both x,y (Two-dimensional array) and for this centroid error value is NaN.

**Comment by maasencioh** [comment]
Hello @anomepani, this is really unexpected, can you share your dataset? I'll need to reproduce the error

**Comment by anomepani** [comment]
I figured it out it actually due to  `options.initialization` value which is `mostDistant` default. As I have passed  `options.initialization`  value to `random` it solved my problem. As per [ml-kmeans API Doc](https://mljs.github.io/kmeans/).
